Remove test report for wasm test

diff --git a/.github/workflows/windows_wasm.yml b/.github/workflows/windows_wasm.yml
--- a/.github/workflows/windows_wasm.yml
+++ b/.github/workflows/windows_wasm.yml
@@ -24,13 +24,14 @@ jobs:
         run: cmake --build target
       - name: Test
         run: ctest --test-dir target -j10 -C Release -T test --output-on-failure
-      - name: Test Report
-        uses: dorny/test-reporter@v1
-        if: success() || failure()
-        with:
-          name: Windows CityHash Test Report
-          path: target/test/test_*_report.xml
-          reporter: java-junit
+      # No test report for the moment
+      # - name: Test Report
+      #   uses: dorny/test-reporter@v1
+      #   if: success() || failure()
+      #   with:
+      #     name: Windows CityHash Test Report
+      #     path: target/test/test_*_report.xml
+      #     reporter: java-junit
       - name: Release
         run: |
           xcopy target\test\test_cityhash.js release\ /s /y
